"use client";
import { Poppins } from "next/font/google";
import { Provider } from "jotai";
import "./globals.css";
import { JotaiProvider, store } from "@repo/store";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <JotaiProvider store={store}>
        <body className={poppins.className}>{children}</body>
      </JotaiProvider>
    </html>
  );
}
